// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7xPaFrW__ZRKjRFe0X-Wp5wZp71jPMKM',
    appId: '1:72412029840:web:b52c0312d7e233155b4915',
    messagingSenderId: '72412029840',
    projectId: 'stat-tracker-team-gen',
    authDomain: 'stat-tracker-team-gen.firebaseapp.com',
    storageBucket: 'stat-tracker-team-gen.appspot.com',
    measurementId: 'G-TK8VKDWX5R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ6q8z-MM3aWeJpqwJJziAR1quyN_p9yM',
    appId: '1:72412029840:android:c064f0c8b7e7d35f5b4915',
    messagingSenderId: '72412029840',
    projectId: 'stat-tracker-team-gen',
    storageBucket: 'stat-tracker-team-gen.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADqmZlJfjoSoqB6wpz5MODNDbNh07I6PI',
    appId: '1:72412029840:ios:e770fc7fdf39c86c5b4915',
    messagingSenderId: '72412029840',
    projectId: 'stat-tracker-team-gen',
    storageBucket: 'stat-tracker-team-gen.appspot.com',
    iosClientId:
        '72412029840-eb2u6nl0cv0laij029iv6f4oiqlfg2k8.apps.googleusercontent.com',
    iosBundleId: 'com.example.stat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADqmZlJfjoSoqB6wpz5MODNDbNh07I6PI',
    appId: '1:72412029840:ios:e770fc7fdf39c86c5b4915',
    messagingSenderId: '72412029840',
    projectId: 'stat-tracker-team-gen',
    storageBucket: 'stat-tracker-team-gen.appspot.com',
    iosClientId:
        '72412029840-eb2u6nl0cv0laij029iv6f4oiqlfg2k8.apps.googleusercontent.com',
    iosBundleId: 'com.example.stat',
  );
}
